// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akxdzgbhpwtfkgqtswsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFreGR6Z2JocHd0ZmtncXRzd3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExMTAzOTEsImV4cCI6MjA2NjY4NjM5MX0.WMkV91u5xHYuV3Z41ctdABtqUjCKqYRiLJWw6iMDUFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);